---
- name: 00 - Hello World / Setup Verification
  hosts: servers
  become: true # Execute as sudo
  tasks:
    - name: Ping connectivity
      ansible.builtin.ping:

    - name: Install Neofetch (to verify apt module)
      ansible.builtin.apt:
        name: fastfetch
        state: present
        update_cache: yes

    - name: Create a welcome file
      ansible.builtin.copy:
        content: "Asible managed this filen on {{ ansible_date_time.date }}!"
        dest: /etc/ansible_managed_check.txt