services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: always
    ports:
      - "8080:80" # Access via http://IP:8080
    volumes:
      - /mnt/data/docker/dashy/conf.yml:/app/public/conf.yml
    environment:
      - NODE_ENV=production
      # FORCE Node to use up to 2GB RAM
      - NODE_OPTIONS=--max-old-space-size=2048
    deploy:
      resources:
        limits:
          # Increase container hard limit to match
          memory: 2G